### ISSUE TITLE
Images are rotated wrongly 

### ISSUE THREAD

**Issue by hptk** [0Supa/uploader#4]
I’m uploading from safari on iOS 17.3.1

look at my cat: https://gachi.gay/W3wcK

the image isn’t supposed to be rotated this way, in my image library it is correct but gets turned during upload.

**Comment by 0Supa** [comment]
This is caused by your phone's camera app storing the image's orientation tag as Exif data, which is now entirely stripped by default. Until a fix is implemented, as a workaround, you can disable the 'Strip Exif data' option, as modern phones will strip sensitive Exif tags before even reaching the browser anyway.

**Comment by 0Supa** [comment]
Entirely stripping the Exif segment is no longer done by default.
